/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperAdminRouteRouteImport } from './routes/super-admin/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as SuperAdminApiStatusRouteImport } from './routes/super-admin/api-status'
import { Route as AuthSignOutRouteImport } from './routes/_auth/sign-out'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as SuperAdminTasksRouteRouteImport } from './routes/super-admin/tasks/route'
import { Route as SuperAdminIntegrationTestRouteRouteImport } from './routes/super-admin/integration-test/route'
import { Route as SuperAdminCountersRouteRouteImport } from './routes/super-admin/counters/route'
import { Route as AppWorkflowsRouteRouteImport } from './routes/_app/workflows/route'
import { Route as AppTasksRouteRouteImport } from './routes/_app/tasks/route'
import { Route as SuperAdminTasksIndexRouteImport } from './routes/super-admin/tasks/index'
import { Route as SuperAdminIntegrationTestIndexRouteImport } from './routes/super-admin/integration-test/index'
import { Route as SuperAdminCountersIndexRouteImport } from './routes/super-admin/counters/index'
import { Route as AppWorkflowsLiveRouteImport } from './routes/_app/workflows/live'
import { Route as AppWorkflowsAllRouteImport } from './routes/_app/workflows/all'
import { Route as AppTasksLiveRouteImport } from './routes/_app/tasks/live'
import { Route as AppTasksFailedRouteImport } from './routes/_app/tasks/failed'
import { Route as AppTasksCompletedRouteImport } from './routes/_app/tasks/completed'
import { Route as AppTasksAllRouteImport } from './routes/_app/tasks/all'

const SuperAdminRouteRoute = SuperAdminRouteRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const SuperAdminApiStatusRoute = SuperAdminApiStatusRouteImport.update({
  id: '/api-status',
  path: '/api-status',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const AuthSignOutRoute = AuthSignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const SuperAdminTasksRouteRoute = SuperAdminTasksRouteRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const SuperAdminIntegrationTestRouteRoute =
  SuperAdminIntegrationTestRouteRouteImport.update({
    id: '/integration-test',
    path: '/integration-test',
    getParentRoute: () => SuperAdminRouteRoute,
  } as any)
const SuperAdminCountersRouteRoute = SuperAdminCountersRouteRouteImport.update({
  id: '/counters',
  path: '/counters',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const AppWorkflowsRouteRoute = AppWorkflowsRouteRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTasksRouteRoute = AppTasksRouteRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRouteRoute,
} as any)
const SuperAdminTasksIndexRoute = SuperAdminTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminTasksRouteRoute,
} as any)
const SuperAdminIntegrationTestIndexRoute =
  SuperAdminIntegrationTestIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SuperAdminIntegrationTestRouteRoute,
  } as any)
const SuperAdminCountersIndexRoute = SuperAdminCountersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminCountersRouteRoute,
} as any)
const AppWorkflowsLiveRoute = AppWorkflowsLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AppWorkflowsRouteRoute,
} as any)
const AppWorkflowsAllRoute = AppWorkflowsAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => AppWorkflowsRouteRoute,
} as any)
const AppTasksLiveRoute = AppTasksLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AppTasksRouteRoute,
} as any)
const AppTasksFailedRoute = AppTasksFailedRouteImport.update({
  id: '/failed',
  path: '/failed',
  getParentRoute: () => AppTasksRouteRoute,
} as any)
const AppTasksCompletedRoute = AppTasksCompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => AppTasksRouteRoute,
} as any)
const AppTasksAllRoute = AppTasksAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => AppTasksRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/super-admin': typeof SuperAdminRouteRouteWithChildren
  '/tasks': typeof AppTasksRouteRouteWithChildren
  '/workflows': typeof AppWorkflowsRouteRouteWithChildren
  '/super-admin/counters': typeof SuperAdminCountersRouteRouteWithChildren
  '/super-admin/integration-test': typeof SuperAdminIntegrationTestRouteRouteWithChildren
  '/super-admin/tasks': typeof SuperAdminTasksRouteRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/login': typeof AuthLoginRoute
  '/sign-out': typeof AuthSignOutRoute
  '/super-admin/api-status': typeof SuperAdminApiStatusRoute
  '/': typeof AppIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/tasks/all': typeof AppTasksAllRoute
  '/tasks/completed': typeof AppTasksCompletedRoute
  '/tasks/failed': typeof AppTasksFailedRoute
  '/tasks/live': typeof AppTasksLiveRoute
  '/workflows/all': typeof AppWorkflowsAllRoute
  '/workflows/live': typeof AppWorkflowsLiveRoute
  '/super-admin/counters/': typeof SuperAdminCountersIndexRoute
  '/super-admin/integration-test/': typeof SuperAdminIntegrationTestIndexRoute
  '/super-admin/tasks/': typeof SuperAdminTasksIndexRoute
}
export interface FileRoutesByTo {
  '/tasks': typeof AppTasksRouteRouteWithChildren
  '/workflows': typeof AppWorkflowsRouteRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/login': typeof AuthLoginRoute
  '/sign-out': typeof AuthSignOutRoute
  '/super-admin/api-status': typeof SuperAdminApiStatusRoute
  '/': typeof AppIndexRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/tasks/all': typeof AppTasksAllRoute
  '/tasks/completed': typeof AppTasksCompletedRoute
  '/tasks/failed': typeof AppTasksFailedRoute
  '/tasks/live': typeof AppTasksLiveRoute
  '/workflows/all': typeof AppWorkflowsAllRoute
  '/workflows/live': typeof AppWorkflowsLiveRoute
  '/super-admin/counters': typeof SuperAdminCountersIndexRoute
  '/super-admin/integration-test': typeof SuperAdminIntegrationTestIndexRoute
  '/super-admin/tasks': typeof SuperAdminTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/super-admin': typeof SuperAdminRouteRouteWithChildren
  '/_app/tasks': typeof AppTasksRouteRouteWithChildren
  '/_app/workflows': typeof AppWorkflowsRouteRouteWithChildren
  '/super-admin/counters': typeof SuperAdminCountersRouteRouteWithChildren
  '/super-admin/integration-test': typeof SuperAdminIntegrationTestRouteRouteWithChildren
  '/super-admin/tasks': typeof SuperAdminTasksRouteRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/sign-out': typeof AuthSignOutRoute
  '/super-admin/api-status': typeof SuperAdminApiStatusRoute
  '/_app/': typeof AppIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/_app/tasks/all': typeof AppTasksAllRoute
  '/_app/tasks/completed': typeof AppTasksCompletedRoute
  '/_app/tasks/failed': typeof AppTasksFailedRoute
  '/_app/tasks/live': typeof AppTasksLiveRoute
  '/_app/workflows/all': typeof AppWorkflowsAllRoute
  '/_app/workflows/live': typeof AppWorkflowsLiveRoute
  '/super-admin/counters/': typeof SuperAdminCountersIndexRoute
  '/super-admin/integration-test/': typeof SuperAdminIntegrationTestIndexRoute
  '/super-admin/tasks/': typeof SuperAdminTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/super-admin'
    | '/tasks'
    | '/workflows'
    | '/super-admin/counters'
    | '/super-admin/integration-test'
    | '/super-admin/tasks'
    | '/dashboard'
    | '/login'
    | '/sign-out'
    | '/super-admin/api-status'
    | '/'
    | '/super-admin/'
    | '/tasks/all'
    | '/tasks/completed'
    | '/tasks/failed'
    | '/tasks/live'
    | '/workflows/all'
    | '/workflows/live'
    | '/super-admin/counters/'
    | '/super-admin/integration-test/'
    | '/super-admin/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/tasks'
    | '/workflows'
    | '/dashboard'
    | '/login'
    | '/sign-out'
    | '/super-admin/api-status'
    | '/'
    | '/super-admin'
    | '/tasks/all'
    | '/tasks/completed'
    | '/tasks/failed'
    | '/tasks/live'
    | '/workflows/all'
    | '/workflows/live'
    | '/super-admin/counters'
    | '/super-admin/integration-test'
    | '/super-admin/tasks'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/super-admin'
    | '/_app/tasks'
    | '/_app/workflows'
    | '/super-admin/counters'
    | '/super-admin/integration-test'
    | '/super-admin/tasks'
    | '/_app/dashboard'
    | '/_auth/login'
    | '/_auth/sign-out'
    | '/super-admin/api-status'
    | '/_app/'
    | '/super-admin/'
    | '/_app/tasks/all'
    | '/_app/tasks/completed'
    | '/_app/tasks/failed'
    | '/_app/tasks/live'
    | '/_app/workflows/all'
    | '/_app/workflows/live'
    | '/super-admin/counters/'
    | '/super-admin/integration-test/'
    | '/super-admin/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  SuperAdminRouteRoute: typeof SuperAdminRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/super-admin/api-status': {
      id: '/super-admin/api-status'
      path: '/api-status'
      fullPath: '/super-admin/api-status'
      preLoaderRoute: typeof SuperAdminApiStatusRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/_auth/sign-out': {
      id: '/_auth/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof AuthSignOutRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/super-admin/tasks': {
      id: '/super-admin/tasks'
      path: '/tasks'
      fullPath: '/super-admin/tasks'
      preLoaderRoute: typeof SuperAdminTasksRouteRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/super-admin/integration-test': {
      id: '/super-admin/integration-test'
      path: '/integration-test'
      fullPath: '/super-admin/integration-test'
      preLoaderRoute: typeof SuperAdminIntegrationTestRouteRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/super-admin/counters': {
      id: '/super-admin/counters'
      path: '/counters'
      fullPath: '/super-admin/counters'
      preLoaderRoute: typeof SuperAdminCountersRouteRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/_app/workflows': {
      id: '/_app/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/super-admin/tasks/': {
      id: '/super-admin/tasks/'
      path: '/'
      fullPath: '/super-admin/tasks/'
      preLoaderRoute: typeof SuperAdminTasksIndexRouteImport
      parentRoute: typeof SuperAdminTasksRouteRoute
    }
    '/super-admin/integration-test/': {
      id: '/super-admin/integration-test/'
      path: '/'
      fullPath: '/super-admin/integration-test/'
      preLoaderRoute: typeof SuperAdminIntegrationTestIndexRouteImport
      parentRoute: typeof SuperAdminIntegrationTestRouteRoute
    }
    '/super-admin/counters/': {
      id: '/super-admin/counters/'
      path: '/'
      fullPath: '/super-admin/counters/'
      preLoaderRoute: typeof SuperAdminCountersIndexRouteImport
      parentRoute: typeof SuperAdminCountersRouteRoute
    }
    '/_app/workflows/live': {
      id: '/_app/workflows/live'
      path: '/live'
      fullPath: '/workflows/live'
      preLoaderRoute: typeof AppWorkflowsLiveRouteImport
      parentRoute: typeof AppWorkflowsRouteRoute
    }
    '/_app/workflows/all': {
      id: '/_app/workflows/all'
      path: '/all'
      fullPath: '/workflows/all'
      preLoaderRoute: typeof AppWorkflowsAllRouteImport
      parentRoute: typeof AppWorkflowsRouteRoute
    }
    '/_app/tasks/live': {
      id: '/_app/tasks/live'
      path: '/live'
      fullPath: '/tasks/live'
      preLoaderRoute: typeof AppTasksLiveRouteImport
      parentRoute: typeof AppTasksRouteRoute
    }
    '/_app/tasks/failed': {
      id: '/_app/tasks/failed'
      path: '/failed'
      fullPath: '/tasks/failed'
      preLoaderRoute: typeof AppTasksFailedRouteImport
      parentRoute: typeof AppTasksRouteRoute
    }
    '/_app/tasks/completed': {
      id: '/_app/tasks/completed'
      path: '/completed'
      fullPath: '/tasks/completed'
      preLoaderRoute: typeof AppTasksCompletedRouteImport
      parentRoute: typeof AppTasksRouteRoute
    }
    '/_app/tasks/all': {
      id: '/_app/tasks/all'
      path: '/all'
      fullPath: '/tasks/all'
      preLoaderRoute: typeof AppTasksAllRouteImport
      parentRoute: typeof AppTasksRouteRoute
    }
  }
}

interface AppTasksRouteRouteChildren {
  AppTasksAllRoute: typeof AppTasksAllRoute
  AppTasksCompletedRoute: typeof AppTasksCompletedRoute
  AppTasksFailedRoute: typeof AppTasksFailedRoute
  AppTasksLiveRoute: typeof AppTasksLiveRoute
}

const AppTasksRouteRouteChildren: AppTasksRouteRouteChildren = {
  AppTasksAllRoute: AppTasksAllRoute,
  AppTasksCompletedRoute: AppTasksCompletedRoute,
  AppTasksFailedRoute: AppTasksFailedRoute,
  AppTasksLiveRoute: AppTasksLiveRoute,
}

const AppTasksRouteRouteWithChildren = AppTasksRouteRoute._addFileChildren(
  AppTasksRouteRouteChildren,
)

interface AppWorkflowsRouteRouteChildren {
  AppWorkflowsAllRoute: typeof AppWorkflowsAllRoute
  AppWorkflowsLiveRoute: typeof AppWorkflowsLiveRoute
}

const AppWorkflowsRouteRouteChildren: AppWorkflowsRouteRouteChildren = {
  AppWorkflowsAllRoute: AppWorkflowsAllRoute,
  AppWorkflowsLiveRoute: AppWorkflowsLiveRoute,
}

const AppWorkflowsRouteRouteWithChildren =
  AppWorkflowsRouteRoute._addFileChildren(AppWorkflowsRouteRouteChildren)

interface AppRouteRouteChildren {
  AppTasksRouteRoute: typeof AppTasksRouteRouteWithChildren
  AppWorkflowsRouteRoute: typeof AppWorkflowsRouteRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppTasksRouteRoute: AppTasksRouteRouteWithChildren,
  AppWorkflowsRouteRoute: AppWorkflowsRouteRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignOutRoute: typeof AuthSignOutRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignOutRoute: AuthSignOutRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface SuperAdminCountersRouteRouteChildren {
  SuperAdminCountersIndexRoute: typeof SuperAdminCountersIndexRoute
}

const SuperAdminCountersRouteRouteChildren: SuperAdminCountersRouteRouteChildren =
  {
    SuperAdminCountersIndexRoute: SuperAdminCountersIndexRoute,
  }

const SuperAdminCountersRouteRouteWithChildren =
  SuperAdminCountersRouteRoute._addFileChildren(
    SuperAdminCountersRouteRouteChildren,
  )

interface SuperAdminIntegrationTestRouteRouteChildren {
  SuperAdminIntegrationTestIndexRoute: typeof SuperAdminIntegrationTestIndexRoute
}

const SuperAdminIntegrationTestRouteRouteChildren: SuperAdminIntegrationTestRouteRouteChildren =
  {
    SuperAdminIntegrationTestIndexRoute: SuperAdminIntegrationTestIndexRoute,
  }

const SuperAdminIntegrationTestRouteRouteWithChildren =
  SuperAdminIntegrationTestRouteRoute._addFileChildren(
    SuperAdminIntegrationTestRouteRouteChildren,
  )

interface SuperAdminTasksRouteRouteChildren {
  SuperAdminTasksIndexRoute: typeof SuperAdminTasksIndexRoute
}

const SuperAdminTasksRouteRouteChildren: SuperAdminTasksRouteRouteChildren = {
  SuperAdminTasksIndexRoute: SuperAdminTasksIndexRoute,
}

const SuperAdminTasksRouteRouteWithChildren =
  SuperAdminTasksRouteRoute._addFileChildren(SuperAdminTasksRouteRouteChildren)

interface SuperAdminRouteRouteChildren {
  SuperAdminCountersRouteRoute: typeof SuperAdminCountersRouteRouteWithChildren
  SuperAdminIntegrationTestRouteRoute: typeof SuperAdminIntegrationTestRouteRouteWithChildren
  SuperAdminTasksRouteRoute: typeof SuperAdminTasksRouteRouteWithChildren
  SuperAdminApiStatusRoute: typeof SuperAdminApiStatusRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

const SuperAdminRouteRouteChildren: SuperAdminRouteRouteChildren = {
  SuperAdminCountersRouteRoute: SuperAdminCountersRouteRouteWithChildren,
  SuperAdminIntegrationTestRouteRoute:
    SuperAdminIntegrationTestRouteRouteWithChildren,
  SuperAdminTasksRouteRoute: SuperAdminTasksRouteRouteWithChildren,
  SuperAdminApiStatusRoute: SuperAdminApiStatusRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}

const SuperAdminRouteRouteWithChildren = SuperAdminRouteRoute._addFileChildren(
  SuperAdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  SuperAdminRouteRoute: SuperAdminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
